import streamlit as st
import requests
import datetime

# from exception.exceptions import TradingBotException
import sys

BASE_URL = "http://localhost:8000"  # Backend endpoint

st.set_page_config(
    page_title="💼 Recruitment Agentic Application",
    page_icon="💼",
    layout="centered",
    initial_sidebar_state="expanded",
)

st.title("💼 Recruitment Agentic Application")

# Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display chat history
st.header("How can I help you in Recruitment? Let me know what you need.")

# Chat input box at bottom
with st.form(key="query_form", clear_on_submit=True):
    user_input = st.text_input("User Input", placeholder="e.g. Find a software engineer in San Francisco")
    submit_button = st.form_submit_button("Send")

if submit_button and user_input.strip():
    try:
        # # Show user message
        # Show thinking spinner while backend processes
        with st.spinner("Bot is thinking..."):
            payload = {"question": user_input}
            print(payload)
            print('wewe dsds')
            response = requests.post(f"{BASE_URL}/query", json=payload)
            print('Response from backend:')
            print(response.status_code, response.text, file=sys.stderr)
        if response.status_code == 200:
            answer = response.json().get("answer", "No answer returned.")
            markdown_content = f"""# 💼 AI Recruitment Plan

            # **Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
            # **Created by:** Mafas Recruitment Agent

            ---

            {answer}

            ---

            *This Recruitment plan was generated by AI. Please verify all information, especially job requirements, candidate qualifications, and interview processes before proceeding with recruitment.*
            """
            st.markdown(markdown_content)
        else:
            st.error(" Bot failed to respond: " + response.text)

    except Exception as e:
        st.error(f"The response failed due to {e}")